- hosts: bm-m3-lab
  vars:
    bml_ilo_username: "{{ lookup('env', 'BML_ILO_USERNAME') }}"
    bml_ilo_password: "{{ lookup('env', 'BML_ILO_PASSWORD') }}"
  tasks:
    - block:
      - name: Check required env vars are set
        fail:
          msg: Ensure that BML_ILO_USERNAME and BML_ILO_PASSWORD environment variables are set
        when: not bml_ilo_username or not bml_ilo_password

      - name: Install dependencies for metal3-dev-env
        apt:
          pkg:
            - make
        become: true

      - name: Add passwordless sudo
        lineinfile:
          path: "/etc/sudoers.d/{{ ansible_user_id}}_passwordless_sudo"
          line: "{{ ansible_user_id }} ALL = (ALL) NOPASSWD: ALL"
          create: true
          owner: root
          group: root
          mode: 0400
        become: true

      - name: Clone the metal3-dev-env repo
        git:
          repo: https://github.com/Nordix/metal3-dev-env.git
          dest: "/home/{{ ansible_user_id }}/metal3-dev-env"
          version: master
          update: no # allows local changes to persist for hacking on the repo
        tags: git

      - name: Copy user config env vars file
        copy:
          src: config.sh
          dest: "/home/{{ ansible_user_id }}/metal3-dev-env/config_{{ ansible_user_id }}.sh"
          mode: 0644

      - name: Clean any existing setup
        shell:
          cmd: "make clean"
          chdir: "/home/{{ ansible_user_id }}/metal3-dev-env/"
        tags: clean

      - name: Reset network
        script: reset_network.sh

      - name: Install requirements for host
        shell:
          cmd: "make install_requirements"
          chdir: "/home/{{ ansible_user_id }}/metal3-dev-env/"
        tags: install_requirements

      - name: Configure host
        shell:
          cmd: "make configure_host"
          chdir: "/home/{{ ansible_user_id }}/metal3-dev-env/"

        # Allowing UDP forwarding allows minikube to use ipmitool (port 623) as
        # well as allowing TFTP traffic outside the host (random port)
      - name: Add UDP forwarding to firewall
        iptables:
          action: append
          chain: FORWARD
          protocol: udp
          jump: ACCEPT
        become: true

        # Workaround for an issue where libvirtd isn't ready for `minikube
        # start` immediately after `systemctl restart libvirtd`
      - name: HACK fix libvirtd restart + dnsmasq race condition with minikube startup
        lineinfile:
          path: "/home/{{ ansible_user_id }}/metal3-dev-env/03_launch_mgmt_cluster.sh"
          insertafter: init_minikube
          line: sleep 2

      - name: Launch management cluster
        shell: 
          cmd: make launch_mgmt_cluster
          chdir: "/home/{{ ansible_user_id }}/metal3-dev-env/"
        tags: launch_mgmt_cluster

      - name: Add interface to provisioning bridge
        shell:
          cmd: "brctl addif provisioning eno1"
        become: true

      - name: Deploy bmhosts
        template:
          src: "templates/bmhosts_crs.yaml.j2"
          dest: "/opt/metal3-dev-env/bmhosts_crs.yaml"

      - name: Apply bmhosts manifest
        shell:
          cmd: kubectl apply -f ./bmhosts_crs.yaml -n metal3
          chdir: "/opt/metal3-dev-env/"
        tags: kubectl_apply
