- hosts: bm-m3-lab
  tasks:
    - block:
      - name: Check that virtualization is supported
        shell: grep -E --color 'vmx|svm' /proc/cpuinfo
        changed_when: false

      - name: Install dependencies for metal3-dev-env
        apt:
          pkg:
            - make
        become: true

      - name: Clone the metal3-dev-env repo
        git:
          repo: https://github.com/metal3-io/metal3-dev-env.git
          dest: /home/estadmin/metal3-dev-env

      # This is a requirement for the metal3-dev-env user
      - name: Add passwordless sudo
        lineinfile:
          path: /etc/sudoers.d/estadmin_passwordless_sudo
          line: "estadmin ALL = (ALL) NOPASSWD: ALL"
          create: true
          owner: root
          group: root
          mode: 0400
        become: true

      - name: Install requirements for host
        shell: 
          cmd: make install_requirements
          chdir: /home/estadmin/metal3-dev-env/
        environment:
          EPHEMERAL_CLUSTER: minikube
      always:
        - name: Remove passwordless sudo
          file:
            path: /etc/sudoers.d/estadmin_passwordless_sudo
            state: absent
          become: true
